default: &default
  adapter:  postgresql
  host:     ""
  encoding: unicode
  pool:     5
  template: template0
  password: <%= ENV['DB_PASS'] %>


development:
  <<: *default
  database: race_registration_development
  password: szymon666
  username: postgres
  host: localhost


test:
  <<: *default
  database: race_registration_test

production:
  <<: *default
  username: myapp
  database: race_registration_production

